name: "web-scraper"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - mongodb_data:/data/db
  app:
    container_name: scraper
    restart: unless-stopped
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=$SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - mongodb

volumes:
  mongodb_data: