# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI web-scraper

on:
  pull_request:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    steps:
    - name: Checkout the repository
      run: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean install project and all packages that it depends on
      run: npm ci
    - name: Build project
      run: npm run build --if-present
    - name: Allow creation of user namespaces (e.g. to the unshare command)
      run: |
        # .. so that we don't get error:
        # unshare: write failed /proc/self/uid_map: Operation not permitted
        # Idea from https://github.com/YoYoGames/GameMaker-Bugs/issues/6015#issuecomment-2135552784 .
        sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
    - run: npm test
